image: python:2.7

stages:
 - build

before_script:
  - "pip install -U platformio"

job:
  stage:
    build
  script:
    make
  artifacts:
    paths:
      - .pio
  tags:
    - docker
    - rancher
